### ISSUE TITLE
Use a single linter (eliminate jscs)

### ISSUE THREAD

**Issue by feross** [feross/standard#45]
Using just a single linter would simplify `standard`, and even speed it up (#43).

`eslint` is excellent, and we've been slowly moving rules from `jscs` to `eslint` whenever possible. There are only a few rules that are unique to `jscs` at this point. The `eslint` project wants to support `jscs` options that make sense, so I think we'll be able to switch entirely very soon. These are the options we're waiting for:

- [x] disallow multiple var declaration (https://github.com/eslint/eslint/issues/1619)
- [ ] Force dot after line break (https://github.com/eslint/eslint/issues/1884)
- [ ] require operator before line break (https://github.com/eslint/eslint/issues/1405)
- [ ] require spaces in for statement (https://github.com/eslint/eslint/issues/1671)

**Comment by feross** [comment]
`eslint` just added a rule for requiring spaces in a for statement. 1 down, just 3 left to go!

Once this issue is fixed, we'll get free JSX support #47, and free speed #43.

**Comment by feross** [comment]
Discussed with @othiym23 and we agreed that it's probably fine to eliminate jscs after the first issue (disallow multiple var declaration (eslint/eslint#1619)) is fixed. The rest are less important, and we can just re-add them when eslint gets them.

**Comment by mightyiam** [comment]
Awesome.

**Comment by feross** [comment]
This is released as 3.3.0.

**Comment by othiym23** [comment]
:tada: don't forget to approve the Bountysource ticket, if you haven't already!

**Comment by feross** [comment]
yep - glad it worked :)

**Comment by mightyiam** [comment]
Entirely awesome.
